In [43]:
import numpy as np

from numpy.random import randint, rand
from numpy.linalg import det

#### Task 1: Array Creation and Manipulation

* Create a 2D NumPy array of shape (3,4) filled with random integers between 1 and 10.
* Print the created array.
* Then, calculate and print the sum of each column.
* Finally, reshape this array into shape (2,6).

In [9]:
arr = randint(1, 10, size=(3, 4))

arr

array([[2, 4, 4, 5],
       [8, 8, 9, 7],
       [9, 5, 8, 1]])

In [16]:
arr.sum(axis=0)

array([19, 17, 21, 13])

In [17]:
arr.reshape((2, 6))

array([[2, 4, 4, 5, 8, 8],
       [9, 7, 9, 5, 8, 1]])

#### Task 2: Indexing, Filtering, and Statistical Analysis

* Generate a 1D NumPy array of 20 random integers between 1 and 100.
* Print the original array.
* Extract and print all elements that are greater than 50 from this array.
* Calculate and print the mean of the array.
* Find and print the position (index) of the minimum value in the array.

In [18]:
arr = randint(1, 100, 20)
arr

array([36, 12, 66,  1, 72, 76,  9, 23, 69, 86, 94,  6, 81, 62, 45, 24, 56,
       55, 56, 12])

In [19]:
arr[arr > 50]

array([66, 72, 76, 69, 86, 94, 81, 62, 56, 55, 56])

In [20]:
arr.mean()

47.05

In [21]:
arr.argmin()

3

#### Task 3: Broadcasting and Arithmetic Operations

* Create two arrays: A, a 2x3 array of random integers between 1 and 10, and B, a 1D array of 3 random integers between 1 and 5.
* Print both arrays.
* Add array B to every row of array A and print the result. (This will test your understanding of broadcasting.)
* Multiply every element of the resulting array by 2 and print the final array.


In [22]:
A = randint(1, 10, (2, 3))
B = randint(1, 5, 3)

In [23]:
A

array([[1, 6, 6],
       [8, 2, 8]])

In [24]:
B

array([2, 2, 3])

In [27]:
C = (A + B) # broadcasting
C

array([[ 3,  8,  9],
       [10,  4, 11]])

In [28]:
C * 2

array([[ 6, 16, 18],
       [20,  8, 22]])

#### Task 4: Linear Algebra Operations

* Create two matrices:
    M1, a 3x3 matrix of random integers between 1 and 10.
    M2, another 3x3 matrix of random integers between 1 and 10.
* Print both matrices.
* Calculate and print the matrix product of M1 and M2.
* Compute and print the transpose of M1.
* Calculate and print the determinant of M2.

In [32]:
M1 = randint(1, 10, (3, 3))
M2 = randint(1, 10, (3, 3))

In [33]:
M1

array([[5, 1, 4],
       [6, 8, 3],
       [9, 7, 8]])

In [34]:
M2

array([[5, 6, 6],
       [5, 8, 3],
       [2, 4, 2]])

In [36]:
np.dot(M1, M2)

array([[ 38,  54,  41],
       [ 76, 112,  66],
       [ 96, 142,  91]])

In [39]:
M1.T # make rows to columns

array([[5, 6, 9],
       [1, 8, 7],
       [4, 3, 8]])

In [42]:
det(M2)

19.99999999999999

#### Task 5: Advanced Array Manipulation and Statistics

* Create a 2D NumPy array of shape (5, 5) filled with random floats between 0 and 1.
* Print the original array.
* Replace all elements in the array that are less than 0.5 with 0, and print the modified array.
* Calculate and print the mean and standard deviation of the modified array.
* Flatten the modified array into a 1D array and print it.

In [51]:
arr = rand(5, 5)

In [52]:
arr

array([[0.37220417, 0.3571765 , 0.34919861, 0.68189868, 0.29154659],
       [0.23249364, 0.01934364, 0.66828402, 0.75496041, 0.72298492],
       [0.93310518, 0.32635417, 0.50033807, 0.10130642, 0.23803182],
       [0.01393203, 0.91007835, 0.87203808, 0.81081159, 0.25881039],
       [0.95567196, 0.35596875, 0.7794585 , 0.11151582, 0.9454154 ]])

In [53]:
arr[arr < 0.5] = 0.0

In [54]:
arr

array([[0.        , 0.        , 0.        , 0.68189868, 0.        ],
       [0.        , 0.        , 0.66828402, 0.75496041, 0.72298492],
       [0.93310518, 0.        , 0.50033807, 0.        , 0.        ],
       [0.        , 0.91007835, 0.87203808, 0.81081159, 0.        ],
       [0.95567196, 0.        , 0.7794585 , 0.        , 0.9454154 ]])

In [55]:
arr.mean()

0.3814018070699428

In [56]:
arr.std()

0.40740078368434784

In [58]:
arr.flatten() # creates a copy of the array

array([0.        , 0.        , 0.        , 0.68189868, 0.        ,
       0.        , 0.        , 0.66828402, 0.75496041, 0.72298492,
       0.93310518, 0.        , 0.50033807, 0.        , 0.        ,
       0.        , 0.91007835, 0.87203808, 0.81081159, 0.        ,
       0.95567196, 0.        , 0.7794585 , 0.        , 0.9454154 ])

In [59]:
arr.ravel() # attempts to return a view of the original array (more memory efficient)

array([0.        , 0.        , 0.        , 0.68189868, 0.        ,
       0.        , 0.        , 0.66828402, 0.75496041, 0.72298492,
       0.93310518, 0.        , 0.50033807, 0.        , 0.        ,
       0.        , 0.91007835, 0.87203808, 0.81081159, 0.        ,
       0.95567196, 0.        , 0.7794585 , 0.        , 0.9454154 ])

#### Task 6: Data Filtering and Aggregation

* Create a 2D NumPy array of shape (6, 4) filled with random integers between 10 and 100.
* Print the original array.
* Filter out and print all rows where the first column is greater than 50.
* For these filtered rows, calculate and print the average of the second column.

In [60]:
arr = randint(10, 100, (6, 4))
arr

array([[52, 13, 51, 79],
       [56, 39, 77, 18],
       [73, 96, 22, 12],
       [56, 72, 54, 73],
       [39, 14, 24, 69],
       [37, 93, 22, 34]])

In [66]:
filtered_arr = arr[arr[:,0] > 50]
filtered_arr

array([[52, 13, 51, 79],
       [56, 39, 77, 18],
       [73, 96, 22, 12],
       [56, 72, 54, 73]])

In [68]:
filtered_arr[:,1].mean()

55.0

#### Task 7: Working with Multi-Dimensional Slicing and Complex Conditions

* Create a 3D NumPy array of shape (3, 4, 2) filled with random integers between 0 and 9.
* Print the original array.
* From this array, extract and print a 2D slice that consists of the second and third rows (index 1 and 2) of the second 'layer' (index 1) of each 3D block.
* Replace all elements in this 2D slice that are greater than 5 with 5, and print the modified slice.

In [80]:
arr = randint(0, 9, (3, 4, 2))
arr

array([[[6, 3],
        [6, 8],
        [5, 7],
        [2, 5]],

       [[1, 5],
        [8, 7],
        [5, 0],
        [1, 7]],

       [[7, 8],
        [3, 0],
        [0, 7],
        [1, 3]]])

In [81]:
slice = arr[:,1:3,1]
slice

array([[8, 7],
       [7, 0],
       [0, 7]])

In [82]:
slice[slice > 5]

array([8, 7, 7, 7])

In [83]:
np.where(slice > 5, 5, slice)

array([[5, 5],
       [5, 0],
       [0, 5]])

In [84]:
slice.ndim

2

In [85]:
arr.ndim

3